pub mod agent;
pub mod app;
mod commands;
pub mod config;
pub mod diffgen;
pub mod envinfo;
mod fsutil;
mod inputline;
mod markdown;
pub mod memory;
pub mod paths;
pub mod perms;
pub mod providers;
pub mod session;
pub mod sysprompt;
mod theme;
pub mod tools;
mod transcript;
pub mod tui;
mod ui_text;
mod uirender;
